version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    webserver:
        restart: always
        image: airflow-image:1.10.4
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY=E8W_AV0Z3itMs6MdNjhek2avY-i24dig46eG9LdUPEM=
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

   selenium-hub:
        restart: always
        image: selenium/hub:latest
        container_name: selenium-hub
        ports:
            - "4444:4444"

    chrome:
        restart: always
        image: selenium/node-chrome-debug:latest
        ports:
            - "5900-5999:5900"
        depends_on:
            - selenium-hub
        environment:
            HUB_HOST: selenium-hub
            HUB_PORT_4444_TCP_ADDR: selenium-hub
            HUB_PORT_4444_TCP_PORT: 4444
            DBUS_SESSION_BUS_ADDRESS: "/dev/null"
        links:
            - selenium-hub:hub
